### ISSUE TITLE
Speed up reconfiguration

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#117]
Reconfiguration, which occurs after any change in the admin, takes upwards of 30 seconds on the demo server. It's doing a bunch of work it shouldn't be doing.

The fix may be as simple as *not* running `initialize` on reconfigure.

**Comment by mgax** [comment]
Maybe add specific ansible tags for specific reconfiguration tasks.

**Comment by mgax** [comment]
Done, but it could use some exhaustive testing.

**Comment by gabriel-v** [comment]
works fast, thanks
