### ISSUE TITLE
Nightly odroid c2 image doesn't boot

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#24]
With the latest nightly (20170730) the boot process hangs in initrd which complains that it can't find the root partition by uuid. The image from [20170721](https://liquidinvestigations.org/images/nightly/oldversions/liquid-20170721-aarch64-odroid_c2.img.xz) works fine.

**Comment by gabriel-v** [comment]
Fixed, see liquidinvestigations/liquidinvestigations#60
