### ISSUE TITLE
Run python scripts in django context

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#31]
In Ansible, in some scripts (e.g. [here](https://github.com/liquidinvestigations/setup/blob/817cdf34b13ee22586ef784a9ad03396abc34aaf/ansible/roles/liquid-core/templates/initialize.d/liquid-core-devel.sh)), we run python code in the django shell. We need a cleaner way to run such code, e.g. a management command that runs a given python script.

**Comment by gabriel-v** [comment]
just use management commands
