### ISSUE TITLE
Single API endpoint for initial wizard

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#52]
Talking to the UI guys about the initial setup wizard, the current approach of hitting several API endpoints to save the configuration is kind of fragile. Can we modify the `/api/registration` to receive all the configuration data in one go?

**Comment by mgax** [comment]
@m-nic, I just had a chat with @gabriel-v, we can do the `/api/registration` endpoint: on GET it will provide default values for the wizard (so forget what i said about hardcoding them) and on POST it will save the wizard's output.

**Comment by gabriel-v** [comment]
done, thanks
