### ISSUE TITLE
Update base odroid c2 images

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/setup#76]
Hardkernel have published new images since we copied the base image, let's bring our copy up to date.

https://odroid.in/ubuntu_16.04lts/

**Comment by mrc-toader** [comment]
Haunted new odroid images.
- first boot - kernel panic
- second boot - hanged 5 minutes on network discovery job (cable was unplugged), found it turned off
- third boot - just works
I'm confused, will check with the other devices.

**Comment by mrc-toader** [comment]
To set up new branch in the setup repo with updated base image.

**Comment by mrc-toader** [comment]
Merged into master.
https://github.com/liquidinvestigations/setup/pull/86
