### ISSUE TITLE
Use "lastStableBuild" not "lastSuccessfullBuild"

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/setup#87]
The "lastStableBuild" is the one that passed all tests. The "lastSuccessfullBuild" is just the one that got built.

We should use "lastStableBuild" urls in all jenkinsfiles of setup (both for prerequisites and for cloud images).
We should update all download links from our download pages and docs to point to "lastStableBuild" urls.

We should investigate if there's a way to force jenkins to keep at least 1 stable build (instead of just keeping the last 3 successful builds, as it is set up now).

**Comment by gabriel-v** [comment]
Or just make all builds fail if the tests fail.

**Comment by mgax** [comment]
Yeah the 2nd option makes more sense. I think if we let pytest fail normally, and collect the xunit file in a finally block, we're good.

**Comment by mgax** [comment]
@gabriel-v So I propose we close this issue, and whenever we see a yellow "unstable" build in Jenkins, because of failed tests, we modify the repo's Jenkinsfile to fail if any tests fail, but still collect results in the "finally" block. If you agree just close this issue.
